keys:
  - &absolutecinema age1l2jngfzmqp7gersl7td8lqkrap7yy3jf348rm22h4tp5sh2fny7qz52p0w # your machine's age public key
  - &z13 age12zlz6lvcdk6eqaewfylg35w0syh58sm7gh53q5vvn7hd7c6nngyseftjxl   # laptop's age key
  - &primeincarnon age12zlz6lvcdk6eqaewfylg35w0syh58sm7gh53q5vvn7hd7c6nngyseftjxl
creation_rules:
  - path_regex: secrets/.*
    key_groups:
      - age: 
        - *z13
        - *absolutecinema
        - *primeincarnon

